# Generated by Django 2.0.4 on 2018-05-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='subtype',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
