# Generated by Django 2.0.4 on 2018-05-01 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beerApp', '0002_auto_20180501_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='subtype',
        ),
    ]
